// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARocKoGEPx8xmwpfGC4mJzeOfyRBa-Syo',
    appId: '1:54523558004:web:9d6c463c57e263508cb921',
    messagingSenderId: '54523558004',
    projectId: 'my-utra-alinghawa',
    authDomain: 'my-utra-alinghawa.firebaseapp.com',
    storageBucket: 'my-utra-alinghawa.firebasestorage.app',
    measurementId: 'G-J9K1XEN66X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUxfP0q8LA4ivU5lGaL61kHIVGvDQVo0',
    appId: '1:54523558004:android:1cb47969768be50c8cb921',
    messagingSenderId: '54523558004',
    projectId: 'my-utra-alinghawa',
    storageBucket: 'my-utra-alinghawa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARc8clMb8qpE5y1CnBir-0lpeiGUsuhYY',
    appId: '1:54523558004:ios:08db26ccc4efbb218cb921',
    messagingSenderId: '54523558004',
    projectId: 'my-utra-alinghawa',
    storageBucket: 'my-utra-alinghawa.firebasestorage.app',
    iosBundleId: 'com.example.activity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARc8clMb8qpE5y1CnBir-0lpeiGUsuhYY',
    appId: '1:54523558004:ios:08db26ccc4efbb218cb921',
    messagingSenderId: '54523558004',
    projectId: 'my-utra-alinghawa',
    storageBucket: 'my-utra-alinghawa.firebasestorage.app',
    iosBundleId: 'com.example.activity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARocKoGEPx8xmwpfGC4mJzeOfyRBa-Syo',
    appId: '1:54523558004:web:41745374f1ee65118cb921',
    messagingSenderId: '54523558004',
    projectId: 'my-utra-alinghawa',
    authDomain: 'my-utra-alinghawa.firebaseapp.com',
    storageBucket: 'my-utra-alinghawa.firebasestorage.app',
    measurementId: 'G-TCG1TKVZ34',
  );
}
